"""Compose-scoped control credentials and explicit deployment hardening."""

from __future__ import annotations

import ipaddress
import json
import os
from pathlib import Path
import secrets
import tempfile
from typing import Any, Literal

from filelock import FileLock

from proxy2vpn.core import config


CLIENT_AUTH_FILE = "control-client-auth.json"
MANAGED_AUTH_HEADER = (
    "# Generated by proxy2vpn; credentials in control-client-auth.json."
)


def validate_bind_address(value: str) -> str:
    """Accept an explicit IPv4 or IPv6 address, never a hostname or port."""
    try:
        if "%" in value:
            raise ValueError
        return str(ipaddress.ip_address(value))
    except ValueError:
        raise ValueError("Proxy bind address must be an IPv4 or IPv6 address") from None


def compose_proxy_bind_address(ports: Any) -> str:
    """Preserve the published address of an existing proxy mapping."""
    from proxy2vpn.adapters.compose_utils import iter_port_mappings

    for item in ports or []:
        if not any(target == 8888 for _, target in iter_port_mappings([item])):
            continue
        if isinstance(item, dict):
            address = str(item.get("host_ip") or "0.0.0.0")
        else:
            parts = str(item).split("/")[0].rsplit(":", 2)
            address = parts[0].strip("[]") if len(parts) == 3 else "0.0.0.0"
        # Compose owns interpolation; preserve expressions without guessing.
        if "$" in address:
            return address
        return validate_bind_address(address)
    return "127.0.0.1"


def _private_write(path: Path, content: str) -> None:
    """Atomically replace a regular file using an owner-only temporary file."""
    if path.is_symlink():
        raise ValueError("Refusing to replace a symlinked control credential file")
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def _render_auth(credentials: dict[str, Any]) -> str:
    return (
        MANAGED_AUTH_HEADER
        + "\n"
        + config.CONTROL_AUTH_CONFIG_TEMPLATE.format(
            monitor_password=credentials["monitor"]["password"],
            operator_password=credentials["operator"]["password"],
        )
    )


# @lat: [[lat.md/security#Control Authentication]]
def ensure_control_auth(compose_file: Path, *, replace: bool = False) -> bool:
    """Bootstrap authenticated controls, preserving existing files by default."""
    server_path = config.resolve_control_auth_config(compose_file)
    client_path = server_path.parent / CLIENT_AUTH_FILE
    server_path.parent.mkdir(parents=True, exist_ok=True)
    with FileLock(str(server_path) + ".lock"):
        if server_path.is_symlink() or client_path.is_symlink():
            raise ValueError("Control credential paths must not be symlinks")
        if server_path.exists() and not replace:
            return False
        if server_path.exists() and server_path.read_text().startswith(
            MANAGED_AUTH_HEADER + "\n"
        ):
            try:
                load_control_auth(compose_file, "monitor")
                load_control_auth(compose_file, "operator")
                return False
            except ValueError:
                # Explicit replacement can repair an incomplete managed pair.
                pass
        if client_path.exists() and not replace:
            raise ValueError(
                "Orphaned client credentials; use 'system secure' to migrate"
            )
        credentials = {
            "version": 1,
            "monitor": {
                "username": "proxy2vpn-monitor",
                "password": secrets.token_urlsafe(32),
            },
            "operator": {
                "username": "proxy2vpn-operator",
                "password": secrets.token_urlsafe(32),
            },
        }
        previous = {
            path: path.read_text() if path.exists() else None
            for path in (server_path, client_path)
        }
        if replace:
            for path, content in previous.items():
                if content is not None:
                    _private_write(path.with_name(path.name + ".bak"), content)
        try:
            _private_write(client_path, json.dumps(credentials, indent=2) + "\n")
            _private_write(server_path, _render_auth(credentials))
        except Exception:
            for path, content in previous.items():
                if content is None:
                    path.unlink(missing_ok=True)
                else:
                    _private_write(path, content)
            raise
        return True


def load_control_auth(
    compose_file: Path,
    purpose: Literal["monitor", "operator"],
) -> tuple[str, str] | None:
    """Load generated credentials without guessing credentials for custom files."""
    server_path = config.resolve_control_auth_config(compose_file)
    if not server_path.exists():
        return None
    if server_path.is_symlink():
        raise ValueError("Control credential paths must not be symlinks")
    if not server_path.read_text().startswith(MANAGED_AUTH_HEADER + "\n"):
        return None
    client_path = server_path.parent / CLIENT_AUTH_FILE
    try:
        if client_path.is_symlink():
            raise ValueError
        if os.name == "posix" and client_path.stat().st_mode & 0o077:
            raise ValueError
        if os.name == "posix" and server_path.stat().st_mode & 0o077:
            raise ValueError
        credentials = json.loads(client_path.read_text())
        if credentials["version"] != 1:
            raise ValueError
        for role in ("monitor", "operator"):
            values = credentials[role]
            if values["username"] != f"proxy2vpn-{role}":
                raise ValueError
            password = values["password"]
            if (
                not isinstance(password, str)
                or not password
                or any(
                    c
                    not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"
                    for c in password
                )
            ):
                raise ValueError
        if server_path.read_text() != _render_auth(credentials):
            raise ValueError
        values = credentials[purpose]
        return values["username"], values["password"]
    except (OSError, ValueError, KeyError, TypeError):
        raise ValueError(
            "Generated control credentials are missing, invalid, mismatched, or not private; "
            "restore both control auth files or migrate with "
            "'system secure --replace-control-auth'"
        ) from None
