name: Python Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/python-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/python-tests.yml'
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'

      - name: Check formatting
        run: uv run --with ruff ruff format --check src/ tests/

      - name: Run linter
        run: uv run --with ruff ruff check src/ tests/

  pytest:
    runs-on: ubuntu-latest
    needs: lint-and-format
    if: ${{ !contains(github.event.commits[0].message, '[skip tests]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'

      - name: Validate changelog fragments
        run: uv run --with towncrier towncrier check

      - name: Run tests
        run: uv run --with pytest pytest
